http:
  port: "8081"

db:
  host: "localhost"
  port: "3306"
  user: "myuser"
  password: "mypassword"
  database: "inventory_db"

salesforce:
  username: "my.sf.user@example.com"
  token: "sf-token-placeholder"

activemq:
  username: "admin"
  password: "admin"
  brokerUrl: "tcp://localhost:61616"